compute:
  hypervisors:
    esxmgmt-01a:
      hostname: "esxmgmt-01a.corp.local"
      ipaddress: "192.168.110.151"
      dns: "192.168.110.94"
      credential:
        username: "root"
        password: "VMware1!"
    esxmgmt-02a:
      hostname: "esxmgmt-02a.corp.local"
      ipaddress: "192.168.110.152"
      dns: "192.168.110.94"
      credential:
        username: "root"
        password: "VMware1!"
    esxmgmt-03a:
      hostname: "esxmgmt-03a.corp.local"
      ipaddress: "192.168.110.153"
      dns: "192.168.110.94"
      credential:
        username: "root"
        password: "VMware1!"
    esxmgmt-04a:
      hostname: "esxmgmt-04a.corp.local"
      ipaddress: "192.168.110.154"
      dns: "192.168.110.94"
      credential:
        username: "root"
        password: "VMware1!"
    esxcomp-01a:
      hostname: "esxcomp-01a.corp.local"
      ipaddress: "192.168.110.155"
      dns: "192.168.110.94"
      credential:
        username: "root"
        password: "VMware1!"
    esxcomp-02a:
      hostname: "esxcomp-02a.corp.local"
      ipaddress: "192.168.110.156"
      dns: "192.168.110.94"
      credential:
        username: "root"
        password: "VMware1!"
    esxcomp-03a:
      hostname: "esxcomp-03a.corp.local"
      ipaddress: "192.168.110.157"
      dns: "192.168.110.94"
      credential:
        username: "root"
        password: "VMware1!"
lightwave:
  domain: "photon.local"
  credential:
    username: "administrator"
    password: "VMware1!"
  controllers:
    lightwave-1:
      site: "photon"
      appliance:
        hostref: "esxmgmt-01a"
        datastore: "ds-site-a-nfs01"
        memoryMb: 4096
        cpus: 2
        enable-ssh-root-login: true
        credential:
          username: "root"
          password: "VMware1!"
        network-config:
          network: "NAT=Management Network"
          type: "static"
          hostname: "lightwave.photon.local"
          ipaddress: "192.168.110.94"
          dns: "192.168.110.94"
          ntp: "192.168.110.10"
          netmask: "255.255.255.0"
          gateway: "192.168.110.1"
photon:
  imagestore:
    img-store-1:
      datastore: "ds-site-a-nfs02"
      enableimagestoreforvms: "true"
  cloud:
    hostref1: "esxcomp-01a"
    hostref2: "esxcomp-02a"
    hostref3: "esxcomp-03a"
  syslog:
    ipaddress: "192.168.110.31"
  controllers:
    pc-1:
      appliance:
        hostref: "esxmgmt-02a"
        datastore: "ds-site-a-nfs01"
        memoryMb: 4096
        cpus: 2
        enable-ssh-root-login: true
        credential:
          username: "root"
          password: "VMware1!"
        network-config:
          network: "NAT=Management Network"
          type: "static"
          hostname: "pc-1.photon.local"
          ipaddress: "192.168.110.91"
          netmask: "255.255.255.0"
          dns: "192.168.110.94"
          ntp: "192.168.110.10"
          gateway: "192.168.110.1"
    pc-2:
      appliance:
        hostref: "esxmgmt-03a"
        datastore: "ds-site-a-nfs01"
        memoryMb: 4096
        cpus: 2
        enable-ssh-root-login: true
        credential:
          username: "root"
          password: "VMware1!"
        network-config:
          network: "NAT=Management Network"
          type: "static"
          hostname: "pc-2.photon.local"
          ipaddress: "192.168.110.92"
          netmask: "255.255.255.0"
          dns: "192.168.110.94"
          ntp: "192.168.110.10"
          gateway: "192.168.110.1"
    pc-3:
      appliance:
        hostref: "esxmgmt-04a"
        datastore: "ds-site-a-nfs01"
        memoryMb: 4096
        cpus: 2
        enable-ssh-root-login: true
        credential:
          username: "root"
          password: "VMware1!"
        network-config:
          network: "NAT=Management Network"
          type: "static"
          hostname: "pc-3.photon.local"
          ipaddress: "192.168.110.93"
          netmask: "255.255.255.0"
          dns: "192.168.110.94"
          ntp: "192.168.110.10"
          gateway: "192.168.110.1"
loadBalancer:
  load-balancer-1:
    appliance:
      hostref: "esxmgmt-04a"
      datastore: "ds-site-a-nfs01"
      memoryMb: 2048
      cpus: 2
      enable-ssh-root-login: true
      credential:
        username: "root"
        password: "VMware1!"
      network-config:
        network: "NAT=Management Network"
        type: "static"
        hostname: "photonplatform.corp.local"
        ipaddress: "192.168.110.95"
        netmask: "255.255.255.0"
        dns: "192.168.110.94"
        ntp: "192.168.110.10"
        gateway: "192.168.110.1"
nsxconfig:
  ipaddress: "192.168.110.201"
  credential:
    username: "admin"
    password: "VMware1!"
  privateIpRootCidr: "172.16.0.0/16"
  floatingIpRootRange: "192.168.160.10-192.168.160.100"
  t0RouterId: "61b58b23-a3b5-4183-a3b8-024d77d36c82"
  edgeClusterId: "0e0bffd5-0ff8-4781-a245-fd7614824230"
  overlayTransportZoneId: "219c58f3-bf00-407f-8c66-e1bc43ddb4b3"
  tunnelIpPoolId: "2659cbdb-1397-4d70-bc52-ccd99bf25432"
  hostUplinkPnic: "vmnic1"
  hostUplinkVlanId: "0"
  dnsServerAddresses: "192.168.110.10"
  
